Silence an unused argument warning
machines-in-motion/time_series pull request #2
Opened 2020-03-02 12:35 UTC by luator

## Description
Suppress warning about unused argument `max_length` which otherwise shows up multiple times during a bulid.

**Note:** This is probably not the proper solution. If this variable is unused, can it be removed?

## How I Tested

Clean rebuild, checking that the warning is gone.

## I fulfilled the following requirements

[//]: # "Please make sure you followed these steps before requesting a review."
[//]: # "Check the boxes in the list below, when done."

- [ ] All new code is formatted according to our style guide (for C++ run clang-format, for Python, run flake8 and fix all warnings).
- [ ] All new functions/classes are documented and existing documentation is updated according to changes.
- [ ] No commented code from testing/debugging is kept (unless there is a good reason to keep it).

2020-03-02 12:45 UTC, vincentberenz commented
@luator 

After double checking, seems like indeed, it should be removed from TimeSeriesBases.
Note that this will requires update of the code in the constructors of the time series and the multiprocess time series, e.g.

https://github.com/machines-in-motion/time_series/blob/b5646799843bccb7951493292d61675e0bcf35fa/include/time_series/multiprocess_time_series.hpp#L64

2020-03-02 12:46 UTC, vincentberenz requested changes
removing passing max_lengths as arg of TimeSeriesBase

2020-03-02 15:44 UTC, luator commented
Alright, I'll update this PR to remove it completely.

2020-03-02 15:58 UTC, luator commented
Done.

2020-03-03 08:38 UTC, vincentberenz approved these changes

2020-03-03 10:00 UTC, merged